---
version: '3'

services:
  odoo-postgresql.oauth-master:
    image: 'postgres:9.5'
    networks:
      - odoo.oauth-master
    environment:
      POSTGRES_USER: 'odoo'
      POSTGRES_PASSWORD: 'odoo'
    volumes:
      - 'odoo-postgresql-data.oauth-master:/var/lib/postgresql/data:rw,Z'
    restart: always

  odoo.oauth-master:
    image: 'docker.groventure.com/gronex/odoo:upstream-10.0'
    expose:
      - '8069'
    networks:
      - nginx
      - odoo.oauth-master
    links:
      - 'odoo-postgresql.oauth-master:postgres'
    environment:
      VIRTUAL_HOST: 'odoo.oauth-master'
      VIRTUAL_PORT: '8069'
      PGUSER: 'odoo'
      PGPASSWORD: 'odoo'
    volumes:
      - 'odoo-data.oauth-master:/var/lib/odoo:rw,Z'
      - '../../test-certs/root.pem:/etc/ssl/certs/97ef0669.0:ro,Z'
    user: root
    command:
      - 'bash'
      - '-c'
      - >
        echo $PGUSER &&
        update-ca-certificates &&
        exec su - odoo
        --preserve-environment
        --shell /bin/bash
        -c 'exec /odoo serve --single'
    depends_on:
      - odoo-postgresql.oauth-master
    restart: always

volumes:
  nginx-conf:
  nginx-gen-templates:
  odoo-postgresql-data.oauth-master:
  odoo-data.oauth-master:

networks:
  nginx:
    external:
      name: nginx_nginx
  odoo.oauth-master:
